### ISSUE TITLE
IMPORT execution failure

### ISSUE THREAD

**Issue by nurbles** [paladin-t/my_basic#59]
I created a test file to import that contains this line:
```
z = 3
```
Then I created this script:
```
x = 5
if x = 5 then
  import "testfile"
  'x = x
endif
print "Did we get here?";
```
When the script is executed by MY-BASIC, I get an "Incomplete Structure" error at the end-of-file in the script.  If the `x = x` line is uncommented, then the script runs fine.

We suspect this is related to the issue I reported earlier with the step handler behaving in unexpected ways with both IMPORT and IF statements.  If there's anything I can do to help resolve this, please let me know.

**Comment by paladin-t** [comment]
Fixed. Btw. not related to the previous issue, but a bug of `import` itself.

**Comment by nurbles** [comment]
Thanks!  No longer getting the error from the IMPORT.  However, I'm still getting unexpected step events, as referenced in my new comment to #57 -- With the example above, I never get a step (neither prev nor post) in the IMPORT file and the execution path looks **EXTREMELY** strange and unexpected.  Though the code actually works as expected, only the row/file from the steps seems to be confused.

**Comment by paladin-t** [comment]
Made another patch, explained in #57.

**Comment by nurbles** [comment]
Thanks!  The patch appears to work fine.  Is the limitation of importing a specific file ONCE intended?  If so, maybe there should be a warning or error when a duplicate import statement is detected.  If not, then I think it is broken.  For example, should these files print "we're in the test file"?
**imported.bas**
```
PRINT "we're in the test file"
```
**main.bas**
```
xyz = 0
IF xyz = 123 THEN
  IMPORT "imported.bas"
ENDIF
IMPORT "imported.bas"
```
When I run the code above, the PRINT is never executed.  Again, if this is intentional, then a warning or error is probably in order on the second IMPORT.  If not...

**Comment by paladin-t** [comment]
added a warning.

**Comment by paladin-t** [comment]
Closing this for now.
